export const FACTOR={S:1.05,A:1,B:.92,C:.82,D:.68,JUNK:.45};
const num=(v,d=0)=>{const n=Number(String(v??'').replace(/[,¥￥%\s]/g,''));return Number.isFinite(n)?n:d};
const norm=v=>String(v??'').normalize('NFKC').toLowerCase().replace(/[‐‑‒–—―ーｰ]/g,'-').replace(/[^a-z0-9ぁ-んァ-ヶ一-龠-]+/g,' ').replace(/\s+/g,' ').trim();
const tok=v=>norm(v).split(/[\s\-_/]+/).filter(Boolean);
const jac=(a,b)=>{const A=new Set(tok(a)),B=new Set(tok(b));if(!A.size||!B.size)return 0;let h=0;for(const x of A)if(B.has(x))h++;return h/(A.size+B.size-h)};
const cond=v=>{const c=String(v||'B').toUpperCase();return FACTOR[c]?c:'B'};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const q=(a,p)=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),i=(s.length-1)*p,b=Math.floor(i),r=i-b;return s[b+1]==null?s[b]:s[b]+r*(s[b+1]-s[b])};
const wq=(a,p)=>{const s=[...a].sort((x,y)=>x.v-y.v),t=s.reduce((z,x)=>z+x.w,0)||1;let c=0;for(const x of s){c+=x.w/t;if(c>=p)return x.v}return s.at(-1)?.v||0};
const wm=a=>{const t=a.reduce((z,x)=>z+x.w,0)||1;return a.reduce((z,x)=>z+x.v*x.w,0)/t};
const r500=n=>Math.max(0,Math.round(n/500)*500);
const age=(d,now)=>{const a=new Date(d),b=new Date(now);return Number.isNaN(a.valueOf())?180:Math.max(0,(b-a)/864e5)};
function sim(t,r){let s=0,exact=false;if(norm(t.category)&&norm(t.category)===norm(r.category))s+=.14;if(norm(t.brand)&&norm(t.brand)===norm(r.brand))s+=.24;if(norm(t.model)&&norm(r.model)){if(norm(t.model)===norm(r.model)){s+=.46;exact=true}else s+=.30*jac(t.model,r.model)}s+=.16*jac([t.brand,t.model,t.name].join(' '),[r.brand,r.model,r.name].join(' '));return{score:Math.min(1,s),exact}}
function mad(items){if(items.length<5)return items;const vals=items.map(x=>x.value),m=q(vals,.5),dev=vals.map(v=>Math.abs(v-m)),M=q(dev,.5);if(!M)return items;const lim=3.5*1.4826*M;return items.filter(x=>Math.abs(x.value-m)<=lim)}
export function comparables(target,rows,opt={}){const now=opt.now||new Date(),tf=FACTOR[cond(target.condition)],half=opt.halfLifeDays||365,min=opt.minSimilarity??.34,out=[];for(const r of rows){const price=num(r.sale_price??r.salePrice);if(price<=0)continue;const m=sim(target,r);if(m.score<min)continue;const rf=FACTOR[cond(r.condition)],value=price*(tf/rf),days=age(r.sold_at??r.soldAt,now),rec=Math.exp(-Math.log(2)*days/half),w=Math.max(.03,Math.pow(m.score,2.25)*rec);out.push({...r,rawSalePrice:price,value,matchScore:m.score,exactModel:m.exact,rowCondition:cond(r.condition),ageDays:days,weight:w,daysToSell:num(r.days_to_sell??r.daysToSell)})}return mad(out).sort((a,b)=>(b.matchScore*b.weight)-(a.matchScore*a.weight)).slice(0,opt.maxComps||60)}
export function appraise(target,rows,policy={},opt={}){const comps=comparables(target,rows,opt);if(!comps.length)return{status:'insufficient_data',message:'比較可能な自社取引が見つかりません。'};const w=comps.map(c=>({v:c.value,w:c.weight})),med=wq(w,.5),mean=wm(w),p25=wq(w,.25),p75=wq(w,.75),days=comps.map(c=>c.daysToSell).filter(Boolean),md=days.length?q(days,.5):null,exact=comps.filter(c=>c.exactModel).length/comps.length,recent=comps.filter(c=>c.ageDays<=365).length/comps.length,disp=med?(p75-p25)/med:1,n=clamp(Math.log2(comps.length+1)/Math.log2(21),0,1),confidence=Math.round(100*clamp(.38*n+.28*exact+.18*recent+.16*clamp(1-disp/.75,0,1),.08,.98));const fee=(policy.feeRate??10)/100,margin=(policy.targetMarginRate??22)/100,risk=(policy.riskRate??5)/100,shipping=num(policy.shipping,1200),inspection=num(policy.inspectionCost),hold=(policy.monthlyHoldingRate??1)/100,months=md==null?1:clamp(md/30,.25,6),sale=.65*med+.35*mean,fees=sale*fee,profit=sale*margin,reserve=sale*risk*(1+(100-confidence)/100),holding=sale*hold*months,max=sale-fees-shipping-inspection-profit-reserve-holding,unc=clamp((100-confidence)/100*.18+disp*.12,.04,.24),low=max*(1-unc),high=max*(1+unc*.45),offer=num(policy.offeredPrice),decision=!offer?'NO_OFFER':offer<=low?'BUY':offer<=high?'REVIEW':'PASS';return{status:'ok',target:{...target,condition:cond(target.condition)},comps,stats:{count:comps.length,exactModelCount:comps.filter(c=>c.exactModel).length,median:r500(med),mean:r500(mean),p25:r500(p25),p75:r500(p75),medianDaysToSell:md==null?null:Math.round(md),confidence},economics:{expectedSale:r500(sale),sellingFees:r500(fees),shipping:r500(shipping),inspectionCost:r500(inspection),targetProfit:r500(profit),riskReserve:r500(reserve),holdingCost:r500(holding),recommendedBuyLow:r500(low),recommendedBuyHigh:r500(high),recommendedMaxBuy:r500(max),offeredPrice:r500(offer),decision}}}
export {num as parseNumber};